name: Publish Artifacts

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
          cache: 'gradle'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 585506
          modrinth-id: F1AqcMCK
          modrinth-featured: true
          modrinth-unfeature-mode: intersection
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          version-type: beta
          version-resolver: all
          loaders: |
            fabric
            quilt
